<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tickets Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            padding: 0;
            font-size: 20px;
        }
        .info {
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Tickets Report</h1>
    </div>

    <div class="info">
        <p><strong>Report Period:</strong> {{ $startDate }} to {{ $endDate }}</p>
        <p><strong>Total Tickets:</strong> {{ $totalTickets }}</p>
        <p><strong>Generated:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 10%;">No. Tiket</th>
                <th style="width: 20%;">Subjek</th>
                <th style="width: 12%;">Pelapor</th>
                <th style="width: 8%;">Status</th>
                <th style="width: 10%;">Kategori</th>
                <th style="width: 8%;">Prioritas</th>
                <th style="width: 12%;">Ditangani Oleh</th>
                <th style="width: 10%;">Dibuat</th>
                <th style="width: 10%;">Diselesaikan</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tickets as $ticket)
            @php
                $resolvedDate = null;
                if (in_array($ticket->status, ['resolved', 'closed']) && $ticket->updated_at) {
                    $resolvedDate = $ticket->updated_at->format('Y-m-d H:i');
                }
            @endphp
            <tr>
                <td>{{ $ticket->ticket_number }}</td>
                <td>{{ Str::limit($ticket->subject, 40) }}</td>
                <td>{{ $ticket->reporter_name ?: $ticket->email_from ?: $ticket->user_name }}</td>
                <td>{{ ucfirst(str_replace('_', ' ', $ticket->status)) }}</td>
                <td>{{ $ticket->category ?: '-' }}</td>
                <td>{{ ucfirst($ticket->priority ?: 'normal') }}</td>
                <td>{{ $ticket->assignedUser?->name ?? 'Belum ditugaskan' }}</td>
                <td>{{ $ticket->created_at->format('Y-m-d H:i') }}</td>
                <td>{{ $resolvedDate ?: '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by ITSO Helpdesk System</p>
    </div>
</body>
</html>
